var rule = {
  title: "兔小贝||腾云驾雾",
  host: "https://www.tuxiaobei.com||https://v.%71%71.com",
  homeUrl: "",
  url: "/list/mip-data?typeId=fyclass&page=fypage&callback=||/x/bu/pagesheet/list?_all=1&append=1&channel=fyclass&listpage=1&offset=((fypage-1)*25)&pagesize=25&iarea=-1",
  detailUrl: "/play/fyid||https://node.video.%71%71.com/x/api/float_vinfo2?cid=fyid",
  searchUrl: "/search/index?key=**||https://v.%71%71.com/x/search/?q=**&stag=1",
  searchable: 2,
  quickSearch: 1,
  filterable: 1,
  multi: 1,
  headers: { "User-Agent": "MOBILE_UA||Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36" },
  timeout: 5000,
  class_url: "2&3&4&25||choice&tv&movie&variety&cartoon&child&doco",
  class_name: "儿歌&故事&国学&启蒙||精选&电视剧&电影&综艺&动漫&少儿&纪录片",
  cate_exclude: "应用||会员|游戏|全部",
  推荐: ".pic-list.list-box;.items;.text&&Text;mip-img&&src;.all&&Text;a&&href||.list_item;img&&alt;img&&src;a&&Text;a&&data-float",
  double: true,
  limit: 5,
  play_parse: true,
  lazy: 'js:fetch_params.headers["user-agent"]=IOS_UA;let html=fetch(input,fetch_params);let src=jsp.pdfh(html,"body&&#videoWrap&&video-src");input=src;',
  一级: "json:data.items;name;image;duration_string;video_id||.list_item;img&&alt;img&&src;a&&Text;a&&data-float",
  二级: 'js:VOD={};let d=[],video_list=[],video_lists=[],QZOutputJson;let html=fetch(input,fetch_params);if(/get_playsource/.test(input)){eval(html);let indexList=QZOutputJson.PlaylistItem.indexList;indexList.forEach(function(it){let dataUrl="https://s.video.qq.com/get_playsource?id="+input.match(/id=(\\d*?)&/)[1]+"&plat=2&type=4&data_type=3&range="+it+"&video_type=10&plname=qq&otype=json";eval(fetch(dataUrl,fetch_params));let vdata=QZOutputJson.PlaylistItem.videoPlayList;vdata.forEach(function(item){d.push({title:item.title,pic_url:item.pic,desc:item.episode_number+"\\t\\t\\t播放量："+item.thirdLine,url:item.playUrl});});video_lists=video_lists.concat(vdata);});}else{let json=JSON.parse(html);video_lists=json.c.video_ids;let cid=input.split("cid=")[1];let url="https://v.qq.com/x/cover/"+cid+".html";if(video_lists.length===1){let vid=video_lists[0];url="https://v.qq.com/x/cover/"+cid+"/"+vid+".html";d.push({title:"在线播放",url:url});}else if(video_lists.length>1){for(let i=0;i<video_lists.length;i+=30){video_list.push(video_lists.slice(i,i+30));}video_list.forEach(function(chunk){let o_url="https://union.video.qq.com/fcgi-bin/data?otype=json&tid=682&appid=20001238&appkey=6c03bbe9658448a4&union_platform=1&idlist="+chunk.join(",");let o_html=fetch(o_url,fetch_params);eval(o_html);QZOutputJson.results.forEach(function(item){let parts=item.fields.series_part_title.split(" ")[1];if(!item.fields.title.match(/预告/)){d.push({title:parts?parts:item.fields.title,pic_url:item.fields.pic160x90.replace("/160",""),desc:item.fields.video_checkup_time,url:"https://v.qq.com/x/cover/"+cid+"/"+item.fields.vid+".html",type:item.fields.category_map&&item.fields.category_map.length>1?item.fields.category_map[1]:""});}});});}}let zp=d.filter(function(item){return !(item.title==="1"&&item.type&&item.type!=="正片");});VOD.vod_play_from="腾讯";VOD.vod_play_url=zp.map(function(item){return item.title+"$"+item.url;}).join("#");',
  搜索: 'js:let d=[];pdfa=jsp.pdfa;pdfh=jsp.pdfh;pd=jsp.pd;let html=request(input);let baseList=pdfa(html,"body&&.result_item_v");if(baseList.length>0){baseList.forEach(function(it){let longText=pdfh(it,".result_title&&Text");let shortText=pdfh(it,".sub&&Text");let url=pd(it,"div.result_item_v&&data-id");let img=pd(it,".figure_pic&&src");let fromTag=pdfh(it,".result_source&&Text");let markAlt=pd(it,".mark_v img&&alt");if(fromTag.match(/腾讯/)&&shortText&&!markAlt.match(/预告/)){d.push({title:longText.split(shortText)[0],img:img,url:"https://node.video.qq.com/x/api/float_vinfo2?cid="+url,desc:shortText.replace("(","").replace(")","")});}});}else{let baseLists=pdfa(html,"body&&.list_item");baseLists.forEach(function(it){let longText=pdfh(it,".figure_title&&Text");let shortText=pdfh(it,".figure_desc&&Text");let url=pd(it,".figure_title&&a&&href");let img=pd(it,".figure_pic&&src");let fromTag=pd(it,".source_icon&&alt");let parts=url.split('/');let cid=parts[parts.length-1].replace(".html","");if(!fromTag&&longText){d.push({title:longText,img:img,url:"https://node.video.qq.com/x/api/float_vinfo2?cid="+cid,desc:shortText});}});}setResult(d);'
}